//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawBoard {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    public sealed partial class DrawBoardSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DrawBoardSettings defaultInstance = ((DrawBoardSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DrawBoardSettings())));
        
        public static DrawBoardSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("882")]
        public double WindowWidth {
            get {
                return ((double)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public double WindowHeight {
            get {
                return ((double)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int WinLoseGameCount {
            get {
                return ((int)(this["WinLoseGameCount"]));
            }
            set {
                this["WinLoseGameCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int WinCount {
            get {
                return ((int)(this["WinCount"]));
            }
            set {
                this["WinCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int RankingGameCount {
            get {
                return ((int)(this["RankingGameCount"]));
            }
            set {
                this["RankingGameCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FirstCount {
            get {
                return ((int)(this["FirstCount"]));
            }
            set {
                this["FirstCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SecondCount {
            get {
                return ((int)(this["SecondCount"]));
            }
            set {
                this["SecondCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ThirdCount {
            get {
                return ((int)(this["ThirdCount"]));
            }
            set {
                this["ThirdCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int FourthCount {
            get {
                return ((int)(this["FourthCount"]));
            }
            set {
                this["FourthCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int FifthCount {
            get {
                return ((int)(this["FifthCount"]));
            }
            set {
                this["FifthCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int SixthCount {
            get {
                return ((int)(this["SixthCount"]));
            }
            set {
                this["SixthCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int SeventhCount {
            get {
                return ((int)(this["SeventhCount"]));
            }
            set {
                this["SeventhCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("당첨")]
        public string WinText {
            get {
                return ((string)(this["WinText"]));
            }
            set {
                this["WinText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("꽝")]
        public string LoseText {
            get {
                return ((string)(this["LoseText"]));
            }
            set {
                this["LoseText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("꽝")]
        public string RankingLoseText {
            get {
                return ((string)(this["RankingLoseText"]));
            }
            set {
                this["RankingLoseText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1등")]
        public string FirstText {
            get {
                return ((string)(this["FirstText"]));
            }
            set {
                this["FirstText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2등")]
        public string SecondText {
            get {
                return ((string)(this["SecondText"]));
            }
            set {
                this["SecondText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3등")]
        public string ThirdText {
            get {
                return ((string)(this["ThirdText"]));
            }
            set {
                this["ThirdText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4등")]
        public string FourthText {
            get {
                return ((string)(this["FourthText"]));
            }
            set {
                this["FourthText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5등")]
        public string FifthText {
            get {
                return ((string)(this["FifthText"]));
            }
            set {
                this["FifthText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6등")]
        public string SixthText {
            get {
                return ((string)(this["SixthText"]));
            }
            set {
                this["SixthText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7등")]
        public string SeventhText {
            get {
                return ((string)(this["SeventhText"]));
            }
            set {
                this["SeventhText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double WinLoseTextSize {
            get {
                return ((double)(this["WinLoseTextSize"]));
            }
            set {
                this["WinLoseTextSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double WinLoseNumberTextSize {
            get {
                return ((double)(this["WinLoseNumberTextSize"]));
            }
            set {
                this["WinLoseNumberTextSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double RankingTextSize {
            get {
                return ((double)(this["RankingTextSize"]));
            }
            set {
                this["RankingTextSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double RankingNumberTextSize {
            get {
                return ((double)(this["RankingNumberTextSize"]));
            }
            set {
                this["RankingNumberTextSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF4B0082")]
        public string WinLoseBackgroundColor {
            get {
                return ((string)(this["WinLoseBackgroundColor"]));
            }
            set {
                this["WinLoseBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF4B0082")]
        public string RankingBackgroundColor {
            get {
                return ((string)(this["RankingBackgroundColor"]));
            }
            set {
                this["RankingBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public string WinLoseWinBackgroundColor {
            get {
                return ((string)(this["WinLoseWinBackgroundColor"]));
            }
            set {
                this["WinLoseWinBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public string RankingWinBackgroundColor {
            get {
                return ((string)(this["RankingWinBackgroundColor"]));
            }
            set {
                this["RankingWinBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public string WinLoseLoseBackgroundColor {
            get {
                return ((string)(this["WinLoseLoseBackgroundColor"]));
            }
            set {
                this["WinLoseLoseBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public string RankingLoseBackgroundColor {
            get {
                return ((string)(this["RankingLoseBackgroundColor"]));
            }
            set {
                this["RankingLoseBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEE8AA")]
        public string WinLoseNumberColor {
            get {
                return ((string)(this["WinLoseNumberColor"]));
            }
            set {
                this["WinLoseNumberColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEE8AA")]
        public string RankingNumberColor {
            get {
                return ((string)(this["RankingNumberColor"]));
            }
            set {
                this["RankingNumberColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FF00")]
        public string WinLoseWinColor {
            get {
                return ((string)(this["WinLoseWinColor"]));
            }
            set {
                this["WinLoseWinColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FF00")]
        public string RankingWinColor {
            get {
                return ((string)(this["RankingWinColor"]));
            }
            set {
                this["RankingWinColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public string WinLoseLoseColor {
            get {
                return ((string)(this["WinLoseLoseColor"]));
            }
            set {
                this["WinLoseLoseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public string RankingLoseColor {
            get {
                return ((string)(this["RankingLoseColor"]));
            }
            set {
                this["RankingLoseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public string WinLosePanelColor {
            get {
                return ((string)(this["WinLosePanelColor"]));
            }
            set {
                this["WinLosePanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public string RankingPanelColor {
            get {
                return ((string)(this["RankingPanelColor"]));
            }
            set {
                this["RankingPanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GulimChe")]
        public string SelectedWinLoseFont {
            get {
                return ((string)(this["SelectedWinLoseFont"]));
            }
            set {
                this["SelectedWinLoseFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GulimChe")]
        public string SelectedRankingFont {
            get {
                return ((string)(this["SelectedRankingFont"]));
            }
            set {
                this["SelectedRankingFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double WinVolume {
            get {
                return ((double)(this["WinVolume"]));
            }
            set {
                this["WinVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double LoseVolume {
            get {
                return ((double)(this["LoseVolume"]));
            }
            set {
                this["LoseVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WinSoundPath {
            get {
                return ((string)(this["WinSoundPath"]));
            }
            set {
                this["WinSoundPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoseSoundPath {
            get {
                return ((string)(this["LoseSoundPath"]));
            }
            set {
                this["LoseSoundPath"] = value;
            }
        }
    }
}
